update yml

diff --git a/.github/workflows/pipeline.yml b/.github/workflows/pipeline.yml
--- a/.github/workflows/pipeline.yml
+++ b/.github/workflows/pipeline.yml
@@ -47,14 +47,14 @@ jobs:
             exit 1
         fi
 
-    - name: Install dependencies bonus
-      run: |
-        if [ -f "Makefile" ]; then
-            make bonus
-        else
-            echo "Makefile not found"
-            exit 1
-        fi
+#    - name: Install dependencies bonus
+#      run: |
+#        if [ -f "Makefile" ]; then
+#            make bonus
+#        else
+#            echo "Makefile not found"
+#            exit 1
+#        fi
 
     - name: Set up Python
       uses: actions/setup-python@v2
